// <auto-generated />
using System;
using ESAP.Sirecec.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Oracle.EntityFrameworkCore.Metadata;

#nullable disable

namespace ESAP.Sirecec.Data.Migrations
{
    [DbContext(typeof(DataContext))]
    partial class DataContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 30);

            OracleModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ESAP.Sirecec.Data.Core.BancoPrograma", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool?>("Activo")
                        .HasColumnType("NUMBER(1)");

                    b.Property<DateTime?>("CreadoEl")
                        .HasColumnType("TIMESTAMP(7)");

                    b.Property<int?>("CreadoPor")
                        .HasColumnType("NUMBER(10)");

                    b.Property<DateTime?>("EditadoEl")
                        .HasColumnType("TIMESTAMP(7)");

                    b.Property<int?>("EditadoPor")
                        .HasColumnType("NUMBER(10)");

                    b.Property<DateTime?>("FechaInicio")
                        .HasColumnType("TIMESTAMP(7)");

                    b.Property<string>("Nombre")
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<int?>("Orden")
                        .HasColumnType("NUMBER(10)");

                    b.HasKey("Id");

                    b.ToTable("BancoPrograma");
                });

            modelBuilder.Entity("ESAP.Sirecec.Data.Core.BancoProgramaNucleo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool?>("Activo")
                        .HasColumnType("NUMBER(1)");

                    b.Property<int>("BancoId")
                        .HasColumnType("NUMBER(10)");

                    b.Property<DateTime?>("CreadoEl")
                        .HasColumnType("TIMESTAMP(7)");

                    b.Property<int?>("CreadoPor")
                        .HasColumnType("NUMBER(10)");

                    b.Property<DateTime?>("EditadoEl")
                        .HasColumnType("TIMESTAMP(7)");

                    b.Property<int?>("EditadoPor")
                        .HasColumnType("NUMBER(10)");

                    b.Property<int>("NucleoId")
                        .HasColumnType("NUMBER(10)");

                    b.Property<int?>("Orden")
                        .HasColumnType("NUMBER(10)");

                    b.HasKey("Id");

                    b.ToTable("BancoProgramaNucleo");
                });

            modelBuilder.Entity("ESAP.Sirecec.Data.Core.BancoProgramasNucleos", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)");

                    b.Property<bool?>("Activo")
                        .HasColumnType("NUMBER(1)");

                    b.Property<int>("BancoId")
                        .HasColumnType("NUMBER(10)");

                    b.Property<string>("BancoProgramaNombre")
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<DateTime?>("CreadoEl")
                        .HasColumnType("TIMESTAMP(7)");

                    b.Property<int?>("CreadoPor")
                        .HasColumnType("NUMBER(10)");

                    b.Property<DateTime?>("EditadoEl")
                        .HasColumnType("TIMESTAMP(7)");

                    b.Property<int?>("EditadoPor")
                        .HasColumnType("NUMBER(10)");

                    b.Property<int?>("NucleoId")
                        .HasColumnType("NUMBER(10)");

                    b.Property<string>("NucleoNombre")
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<int?>("Orden")
                        .HasColumnType("NUMBER(10)");

                    b.HasKey("Id");

                    b.ToTable((string)null);

                    b.ToView("BancoProgramasNucleos", (string)null);
                });

            modelBuilder.Entity("ESAP.Sirecec.Data.Core.Clasificador", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool?>("Activo")
                        .HasColumnType("NUMBER(1)");

                    b.Property<DateTime?>("CreadoEl")
                        .HasColumnType("TIMESTAMP(7)");

                    b.Property<int?>("CreadoPor")
                        .HasColumnType("NUMBER(10)");

                    b.Property<string>("Descripcion")
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<DateTime?>("EditadoEl")
                        .HasColumnType("TIMESTAMP(7)");

                    b.Property<int?>("EditadoPor")
                        .HasColumnType("NUMBER(10)");

                    b.Property<string>("Nombre")
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<int?>("Orden")
                        .HasColumnType("NUMBER(10)");

                    b.Property<int?>("PadreId")
                        .HasColumnType("NUMBER(10)");

                    b.Property<int>("TipoId")
                        .HasColumnType("NUMBER(10)");

                    b.HasKey("Id");

                    b.HasIndex("TipoId");

                    b.ToTable("Clasificador");
                });

            modelBuilder.Entity("ESAP.Sirecec.Data.Core.ClasificadorTipo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool?>("Activo")
                        .HasColumnType("NUMBER(1)");

                    b.Property<DateTime?>("CreadoEl")
                        .HasColumnType("TIMESTAMP(7)");

                    b.Property<int?>("CreadoPor")
                        .HasColumnType("NUMBER(10)");

                    b.Property<string>("Descripcion")
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<DateTime?>("EditadoEl")
                        .HasColumnType("TIMESTAMP(7)");

                    b.Property<int?>("EditadoPor")
                        .HasColumnType("NUMBER(10)");

                    b.Property<string>("Nombre")
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<int?>("Orden")
                        .HasColumnType("NUMBER(10)");

                    b.HasKey("Id");

                    b.ToTable("ClasificadorTipo");
                });

            modelBuilder.Entity("ESAP.Sirecec.Data.Core.Clasificadores", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)");

                    b.Property<bool?>("Activo")
                        .HasColumnType("NUMBER(1)");

                    b.Property<DateTime?>("CreadoEl")
                        .HasColumnType("TIMESTAMP(7)");

                    b.Property<int?>("CreadoPor")
                        .HasColumnType("NUMBER(10)");

                    b.Property<string>("Descripcion")
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<DateTime?>("EditadoEl")
                        .HasColumnType("TIMESTAMP(7)");

                    b.Property<int?>("EditadoPor")
                        .HasColumnType("NUMBER(10)");

                    b.Property<int?>("Hijos")
                        .HasColumnType("NUMBER(10)");

                    b.Property<string>("Nombre")
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<int?>("Orden")
                        .HasColumnType("NUMBER(10)");

                    b.Property<int>("PadreId")
                        .HasColumnType("NUMBER(10)");

                    b.Property<string>("PadreNombre")
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<int?>("PadreTipoId")
                        .HasColumnType("NUMBER(10)");

                    b.Property<string>("PadreTipoNombre")
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<int>("TipoId")
                        .HasColumnType("NUMBER(10)");

                    b.Property<string>("TipoNombre")
                        .HasColumnType("NVARCHAR2(2000)");

                    b.HasKey("Id");

                    b.ToTable((string)null);

                    b.ToView("Clasificadores", (string)null);
                });

            modelBuilder.Entity("ESAP.Sirecec.Data.Core.Curso", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool?>("Activo")
                        .HasColumnType("NUMBER(1)");

                    b.Property<int?>("CantidadAulas")
                        .HasColumnType("NUMBER(10)");

                    b.Property<string>("CertificadoCiudad")
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<int?>("CertificadoEtiquetaId")
                        .HasColumnType("NUMBER(10)");

                    b.Property<DateTime>("CertificadoFechaExpedicion")
                        .HasColumnType("TIMESTAMP(7)");

                    b.Property<bool?>("CertificadoVerCiudad")
                        .HasColumnType("NUMBER(1)");

                    b.Property<string>("CodigoVerificacion")
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<string>("Contenidos")
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<string>("CorreoElectronico")
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<DateTime?>("CreadoEl")
                        .HasColumnType("TIMESTAMP(7)");

                    b.Property<int?>("CreadoPor")
                        .HasColumnType("NUMBER(10)");

                    b.Property<int?>("CupoAula")
                        .HasColumnType("NUMBER(10)");

                    b.Property<int?>("CupoTotal")
                        .HasColumnType("NUMBER(10)");

                    b.Property<int?>("DependenciaId")
                        .HasColumnType("NUMBER(10)");

                    b.Property<string>("Descripcion")
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<DateTime?>("EditadoEl")
                        .HasColumnType("TIMESTAMP(7)");

                    b.Property<int?>("EditadoPor")
                        .HasColumnType("NUMBER(10)");

                    b.Property<int?>("EstadoCursoId")
                        .HasColumnType("NUMBER(10)");

                    b.Property<DateTime>("FechaFin")
                        .HasColumnType("TIMESTAMP(7)");

                    b.Property<DateTime>("FechaFinInscripcion")
                        .HasColumnType("TIMESTAMP(7)");

                    b.Property<DateTime>("FechaInicio")
                        .HasColumnType("TIMESTAMP(7)");

                    b.Property<DateTime>("FechaInicioInscripcion")
                        .HasColumnType("TIMESTAMP(7)");

                    b.Property<DateTime>("HoraInicio")
                        .HasColumnType("TIMESTAMP(7)");

                    b.Property<int?>("HorasTotales")
                        .HasColumnType("NUMBER(10)");

                    b.Property<string>("ImagenCertificado")
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<string>("ImagenCurso")
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<int?>("IndicadorId")
                        .HasColumnType("NUMBER(10)");

                    b.Property<bool?>("JornadaManana")
                        .HasColumnType("NUMBER(1)");

                    b.Property<bool?>("JornadaNoche")
                        .HasColumnType("NUMBER(1)");

                    b.Property<bool?>("JornadaTarde")
                        .HasColumnType("NUMBER(1)");

                    b.Property<string>("LugarRealizacion")
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<int?>("MunicipioId")
                        .HasColumnType("NUMBER(10)");

                    b.Property<int?>("NivelId")
                        .HasColumnType("NUMBER(10)");

                    b.Property<string>("Nombre")
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<int?>("NumeroDias")
                        .HasColumnType("NUMBER(10)");

                    b.Property<string>("Objetivos")
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<int?>("Orden")
                        .HasColumnType("NUMBER(10)");

                    b.Property<int?>("PorcentajeValidoAsistencia")
                        .HasColumnType("NUMBER(10)");

                    b.Property<int?>("ProgramaId")
                        .HasColumnType("NUMBER(10)");

                    b.Property<bool?>("Publicado")
                        .HasColumnType("NUMBER(1)");

                    b.Property<string>("Responsable")
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<string>("TelefonoContacto")
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<int?>("TipoAsistenciaId")
                        .HasColumnType("NUMBER(10)");

                    b.Property<int?>("TipoCursoId")
                        .HasColumnType("NUMBER(10)");

                    b.HasKey("Id");

                    b.HasIndex("NivelId");

                    b.ToTable("Curso");
                });

            modelBuilder.Entity("ESAP.Sirecec.Data.Core.CursoAnexo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool?>("Activo")
                        .HasColumnType("NUMBER(1)");

                    b.Property<int>("AnexoId")
                        .HasColumnType("NUMBER(10)");

                    b.Property<DateTime?>("CreadoEl")
                        .HasColumnType("TIMESTAMP(7)");

                    b.Property<int?>("CreadoPor")
                        .HasColumnType("NUMBER(10)");

                    b.Property<int>("CursoId")
                        .HasColumnType("NUMBER(10)");

                    b.Property<DateTime?>("EditadoEl")
                        .HasColumnType("TIMESTAMP(7)");

                    b.Property<int?>("EditadoPor")
                        .HasColumnType("NUMBER(10)");

                    b.Property<int?>("Orden")
                        .HasColumnType("NUMBER(10)");

                    b.Property<int>("TipoId")
                        .HasColumnType("NUMBER(10)");

                    b.HasKey("Id");

                    b.HasIndex("CursoId");

                    b.ToTable("CursoAnexo");
                });

            modelBuilder.Entity("ESAP.Sirecec.Data.Core.CursoEncuesta", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool?>("Activo")
                        .HasColumnType("NUMBER(1)");

                    b.Property<DateTime?>("CreadoEl")
                        .HasColumnType("TIMESTAMP(7)");

                    b.Property<int?>("CreadoPor")
                        .HasColumnType("NUMBER(10)");

                    b.Property<int>("CursoId")
                        .HasColumnType("NUMBER(10)");

                    b.Property<DateTime?>("EditadoEl")
                        .HasColumnType("TIMESTAMP(7)");

                    b.Property<int?>("EditadoPor")
                        .HasColumnType("NUMBER(10)");

                    b.Property<int>("EncuestaId")
                        .HasColumnType("NUMBER(10)");

                    b.Property<int?>("Orden")
                        .HasColumnType("NUMBER(10)");

                    b.HasKey("Id");

                    b.HasIndex("CursoId");

                    b.ToTable("CursoEncuesta");
                });

            modelBuilder.Entity("ESAP.Sirecec.Data.Core.CursoFecha", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool?>("Activo")
                        .HasColumnType("NUMBER(1)");

                    b.Property<DateTime?>("CreadoEl")
                        .HasColumnType("TIMESTAMP(7)");

                    b.Property<int?>("CreadoPor")
                        .HasColumnType("NUMBER(10)");

                    b.Property<int?>("CursoId")
                        .HasColumnType("NUMBER(10)");

                    b.Property<DateTime?>("EditadoEl")
                        .HasColumnType("TIMESTAMP(7)");

                    b.Property<int?>("EditadoPor")
                        .HasColumnType("NUMBER(10)");

                    b.Property<int?>("Orden")
                        .HasColumnType("NUMBER(10)");

                    b.Property<int?>("Ponderacion")
                        .HasColumnType("NUMBER(10)");

                    b.HasKey("Id");

                    b.HasIndex("CursoId");

                    b.ToTable("CursoFecha");
                });

            modelBuilder.Entity("ESAP.Sirecec.Data.Core.CursoTema", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool?>("Activo")
                        .HasColumnType("NUMBER(1)");

                    b.Property<DateTime?>("CreadoEl")
                        .HasColumnType("TIMESTAMP(7)");

                    b.Property<int?>("CreadoPor")
                        .HasColumnType("NUMBER(10)");

                    b.Property<int>("CursoId")
                        .HasColumnType("NUMBER(10)");

                    b.Property<string>("DireccionRealizacion")
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<int>("DocenteId")
                        .HasColumnType("NUMBER(10)");

                    b.Property<DateTime?>("EditadoEl")
                        .HasColumnType("TIMESTAMP(7)");

                    b.Property<int?>("EditadoPor")
                        .HasColumnType("NUMBER(10)");

                    b.Property<string>("LugarRealizacion")
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<int?>("Orden")
                        .HasColumnType("NUMBER(10)");

                    b.Property<int>("TemaId")
                        .HasColumnType("NUMBER(10)");

                    b.HasKey("Id");

                    b.HasIndex("CursoId");

                    b.HasIndex("TemaId");

                    b.ToTable("CursoTema");
                });

            modelBuilder.Entity("ESAP.Sirecec.Data.Core.Cursos", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)");

                    b.Property<bool?>("Activo")
                        .HasColumnType("NUMBER(1)");

                    b.Property<DateTime>("BancoFechaInicio")
                        .HasColumnType("TIMESTAMP(7)");

                    b.Property<int?>("BancoId")
                        .HasColumnType("NUMBER(10)");

                    b.Property<string>("BancoNombre")
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<int?>("CantidadAulas")
                        .HasColumnType("NUMBER(10)");

                    b.Property<string>("CertificadoCiudad")
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<int?>("CertificadoEtiquetaId")
                        .HasColumnType("NUMBER(10)");

                    b.Property<string>("CertificadoEtiquetaNombre")
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<DateTime>("CertificadoFechaExpedicion")
                        .HasColumnType("TIMESTAMP(7)");

                    b.Property<bool?>("CertificadoVerCiudad")
                        .HasColumnType("NUMBER(1)");

                    b.Property<string>("CodigoVerificacion")
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<string>("Contenidos")
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<string>("CorreoElectronico")
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<DateTime?>("CreadoEl")
                        .HasColumnType("TIMESTAMP(7)");

                    b.Property<int?>("CreadoPor")
                        .HasColumnType("NUMBER(10)");

                    b.Property<int?>("CupoAula")
                        .HasColumnType("NUMBER(10)");

                    b.Property<int?>("CupoTotal")
                        .HasColumnType("NUMBER(10)");

                    b.Property<int?>("DepartamentoId")
                        .HasColumnType("NUMBER(10)");

                    b.Property<string>("DepartamentoNombre")
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<int?>("DependenciaId")
                        .HasColumnType("NUMBER(10)");

                    b.Property<string>("DependenciaNombre")
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<string>("Descripcion")
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<DateTime?>("EditadoEl")
                        .HasColumnType("TIMESTAMP(7)");

                    b.Property<int?>("EditadoPor")
                        .HasColumnType("NUMBER(10)");

                    b.Property<int?>("EscuelaId")
                        .HasColumnType("NUMBER(10)");

                    b.Property<string>("EscuelaNombre")
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<int?>("EstadoCursoId")
                        .HasColumnType("NUMBER(10)");

                    b.Property<string>("EstadoCursoNombre")
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<DateTime>("FechaFin")
                        .HasColumnType("TIMESTAMP(7)");

                    b.Property<DateTime>("FechaFinInscripcion")
                        .HasColumnType("TIMESTAMP(7)");

                    b.Property<DateTime>("FechaInicio")
                        .HasColumnType("TIMESTAMP(7)");

                    b.Property<DateTime>("FechaInicioInscripcion")
                        .HasColumnType("TIMESTAMP(7)");

                    b.Property<DateTime>("HoraInicio")
                        .HasColumnType("TIMESTAMP(7)");

                    b.Property<int?>("HorasTotales")
                        .HasColumnType("NUMBER(10)");

                    b.Property<string>("ImagenCertificado")
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<string>("ImagenCurso")
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<int?>("IndicadorId")
                        .HasColumnType("NUMBER(10)");

                    b.Property<string>("IndicadorNombre")
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<bool?>("JornadaManana")
                        .HasColumnType("NUMBER(1)");

                    b.Property<bool?>("JornadaNoche")
                        .HasColumnType("NUMBER(1)");

                    b.Property<bool?>("JornadaTarde")
                        .HasColumnType("NUMBER(1)");

                    b.Property<string>("LugarRealizacion")
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<int?>("MunicipioId")
                        .HasColumnType("NUMBER(10)");

                    b.Property<string>("MunicipioNombre")
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<int?>("NivelId")
                        .HasColumnType("NUMBER(10)");

                    b.Property<string>("NivelNombre")
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<string>("Nombre")
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<DateTime>("NucleoFechaInicio")
                        .HasColumnType("TIMESTAMP(7)");

                    b.Property<int?>("NucleoId")
                        .HasColumnType("NUMBER(10)");

                    b.Property<string>("NucleoNombre")
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<int?>("NumeroDias")
                        .HasColumnType("NUMBER(10)");

                    b.Property<string>("Objetivos")
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<int?>("Orden")
                        .HasColumnType("NUMBER(10)");

                    b.Property<int?>("PaisId")
                        .HasColumnType("NUMBER(10)");

                    b.Property<string>("PaisIso1")
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<string>("PaisIso2")
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<int?>("PorcentajeValidoAsistencia")
                        .HasColumnType("NUMBER(10)");

                    b.Property<int?>("ProductoId")
                        .HasColumnType("NUMBER(10)");

                    b.Property<string>("ProductoNombre")
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<DateTime>("ProgramaFechaInicio")
                        .HasColumnType("TIMESTAMP(7)");

                    b.Property<int?>("ProgramaId")
                        .HasColumnType("NUMBER(10)");

                    b.Property<string>("ProgramaNombre")
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<bool?>("Publicado")
                        .HasColumnType("NUMBER(1)");

                    b.Property<string>("Responsable")
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<string>("TelefonoContacto")
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<int?>("TerritorialId")
                        .HasColumnType("NUMBER(10)");

                    b.Property<string>("TerritorialNombre")
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<int?>("TipoAsistenciaId")
                        .HasColumnType("NUMBER(10)");

                    b.Property<string>("TipoAsistenciaNombre")
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<int?>("TipoCursoId")
                        .HasColumnType("NUMBER(10)");

                    b.Property<string>("TipoCursoNombre")
                        .HasColumnType("NVARCHAR2(2000)");

                    b.HasKey("Id");

                    b.ToTable((string)null);

                    b.ToView("Cursos", (string)null);
                });

            modelBuilder.Entity("ESAP.Sirecec.Data.Core.Departamento", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool?>("Activo")
                        .HasColumnType("NUMBER(1)");

                    b.Property<string>("Codigo")
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<DateTime?>("CreadoEl")
                        .HasColumnType("TIMESTAMP(7)");

                    b.Property<int?>("CreadoPor")
                        .HasColumnType("NUMBER(10)");

                    b.Property<DateTime?>("EditadoEl")
                        .HasColumnType("TIMESTAMP(7)");

                    b.Property<int?>("EditadoPor")
                        .HasColumnType("NUMBER(10)");

                    b.Property<string>("Nombre")
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<int?>("Orden")
                        .HasColumnType("NUMBER(10)");

                    b.Property<int>("PaisId")
                        .HasColumnType("NUMBER(10)");

                    b.Property<int?>("TerritorialId")
                        .HasColumnType("NUMBER(10)");

                    b.HasKey("Id");

                    b.HasIndex("PaisId");

                    b.ToTable("Departamento");
                });

            modelBuilder.Entity("ESAP.Sirecec.Data.Core.DepartamentoMunicipio", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool?>("Activo")
                        .HasColumnType("NUMBER(1)");

                    b.Property<DateTime?>("CreadoEl")
                        .HasColumnType("TIMESTAMP(7)");

                    b.Property<int?>("CreadoPor")
                        .HasColumnType("NUMBER(10)");

                    b.Property<int>("DepartamentoId")
                        .HasColumnType("NUMBER(10)");

                    b.Property<DateTime?>("EditadoEl")
                        .HasColumnType("TIMESTAMP(7)");

                    b.Property<int?>("EditadoPor")
                        .HasColumnType("NUMBER(10)");

                    b.Property<int>("MunicipioId")
                        .HasColumnType("NUMBER(10)");

                    b.Property<int?>("Orden")
                        .HasColumnType("NUMBER(10)");

                    b.HasKey("Id");

                    b.ToTable("DepartamentoMunicipio");
                });

            modelBuilder.Entity("ESAP.Sirecec.Data.Core.DepartamentosMunicipios", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)");

                    b.Property<bool?>("Activo")
                        .HasColumnType("NUMBER(1)");

                    b.Property<DateTime?>("CreadoEl")
                        .HasColumnType("TIMESTAMP(7)");

                    b.Property<int?>("CreadoPor")
                        .HasColumnType("NUMBER(10)");

                    b.Property<int>("DepartamentoId")
                        .HasColumnType("NUMBER(10)");

                    b.Property<string>("DepartamentoNombre")
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<DateTime?>("EditadoEl")
                        .HasColumnType("TIMESTAMP(7)");

                    b.Property<int?>("EditadoPor")
                        .HasColumnType("NUMBER(10)");

                    b.Property<int?>("MunicipioId")
                        .HasColumnType("NUMBER(10)");

                    b.Property<string>("MunicipioNombre")
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<int?>("Orden")
                        .HasColumnType("NUMBER(10)");

                    b.HasKey("Id");

                    b.ToTable((string)null);

                    b.ToView("DepartamentosMunicipios", (string)null);
                });

            modelBuilder.Entity("ESAP.Sirecec.Data.Core.Documento", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool?>("Activo")
                        .HasColumnType("NUMBER(1)");

                    b.Property<string>("Archivo")
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<int>("ClasificacionId")
                        .HasColumnType("NUMBER(10)");

                    b.Property<DateTime?>("CreadoEl")
                        .HasColumnType("TIMESTAMP(7)");

                    b.Property<int?>("CreadoPor")
                        .HasColumnType("NUMBER(10)");

                    b.Property<string>("Descripcion")
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<DateTime?>("EditadoEl")
                        .HasColumnType("TIMESTAMP(7)");

                    b.Property<int?>("EditadoPor")
                        .HasColumnType("NUMBER(10)");

                    b.Property<int>("GrupoId")
                        .HasColumnType("NUMBER(10)");

                    b.Property<string>("Nombre")
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<int?>("Orden")
                        .HasColumnType("NUMBER(10)");

                    b.Property<int>("TipoId")
                        .HasColumnType("NUMBER(10)");

                    b.HasKey("Id");

                    b.ToTable("Documento");
                });

            modelBuilder.Entity("ESAP.Sirecec.Data.Core.Encuesta", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool?>("Activo")
                        .HasColumnType("NUMBER(1)");

                    b.Property<DateTime?>("CreadoEl")
                        .HasColumnType("TIMESTAMP(7)");

                    b.Property<int?>("CreadoPor")
                        .HasColumnType("NUMBER(10)");

                    b.Property<string>("Descripcion")
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<DateTime?>("EditadoEl")
                        .HasColumnType("TIMESTAMP(7)");

                    b.Property<int?>("EditadoPor")
                        .HasColumnType("NUMBER(10)");

                    b.Property<int?>("Orden")
                        .HasColumnType("NUMBER(10)");

                    b.Property<int?>("TipoEncuestaId")
                        .HasColumnType("NUMBER(10)");

                    b.Property<string>("Titulo")
                        .HasColumnType("NVARCHAR2(2000)");

                    b.HasKey("Id");

                    b.ToTable("Encuesta");
                });

            modelBuilder.Entity("ESAP.Sirecec.Data.Core.EncuestaPregunta", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool?>("Activo")
                        .HasColumnType("NUMBER(1)");

                    b.Property<DateTime?>("CreadoEl")
                        .HasColumnType("TIMESTAMP(7)");

                    b.Property<int?>("CreadoPor")
                        .HasColumnType("NUMBER(10)");

                    b.Property<DateTime?>("EditadoEl")
                        .HasColumnType("TIMESTAMP(7)");

                    b.Property<int?>("EditadoPor")
                        .HasColumnType("NUMBER(10)");

                    b.Property<int?>("EncuestaId")
                        .HasColumnType("NUMBER(10)");

                    b.Property<int?>("Orden")
                        .HasColumnType("NUMBER(10)");

                    b.Property<int?>("PreguntaId")
                        .HasColumnType("NUMBER(10)");

                    b.HasKey("Id");

                    b.HasIndex("EncuestaId");

                    b.HasIndex("PreguntaId");

                    b.ToTable("EncuestaPregunta");
                });

            modelBuilder.Entity("ESAP.Sirecec.Data.Core.Escuela", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool?>("Activo")
                        .HasColumnType("NUMBER(1)");

                    b.Property<DateTime?>("CreadoEl")
                        .HasColumnType("TIMESTAMP(7)");

                    b.Property<int?>("CreadoPor")
                        .HasColumnType("NUMBER(10)");

                    b.Property<string>("Descripcion")
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<DateTime?>("EditadoEl")
                        .HasColumnType("TIMESTAMP(7)");

                    b.Property<int?>("EditadoPor")
                        .HasColumnType("NUMBER(10)");

                    b.Property<string>("Nombre")
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<int?>("Orden")
                        .HasColumnType("NUMBER(10)");

                    b.HasKey("Id");

                    b.ToTable("Escuela");
                });

            modelBuilder.Entity("ESAP.Sirecec.Data.Core.Indicador", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool?>("Activo")
                        .HasColumnType("NUMBER(1)");

                    b.Property<DateTime?>("CreadoEl")
                        .HasColumnType("TIMESTAMP(7)");

                    b.Property<int?>("CreadoPor")
                        .HasColumnType("NUMBER(10)");

                    b.Property<string>("Descripcion")
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<DateTime?>("EditadoEl")
                        .HasColumnType("TIMESTAMP(7)");

                    b.Property<int?>("EditadoPor")
                        .HasColumnType("NUMBER(10)");

                    b.Property<string>("Nombre")
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<int?>("Orden")
                        .HasColumnType("NUMBER(10)");

                    b.Property<int?>("ProductoId")
                        .HasColumnType("NUMBER(10)");

                    b.HasKey("Id");

                    b.HasIndex("ProductoId");

                    b.ToTable("Indicador");
                });

            modelBuilder.Entity("ESAP.Sirecec.Data.Core.Modulo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ActividadAprendizaje")
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<string>("ActividadEvaluacion")
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<bool?>("Activo")
                        .HasColumnType("NUMBER(1)");

                    b.Property<DateTime?>("CreadoEl")
                        .HasColumnType("TIMESTAMP(7)");

                    b.Property<int?>("CreadoPor")
                        .HasColumnType("NUMBER(10)");

                    b.Property<string>("Descripcion")
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<DateTime?>("EditadoEl")
                        .HasColumnType("TIMESTAMP(7)");

                    b.Property<int?>("EditadoPor")
                        .HasColumnType("NUMBER(10)");

                    b.Property<string>("Justificacion")
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<string>("Metodologia")
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<string>("Nombre")
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<string>("Objetivos")
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<int?>("Orden")
                        .HasColumnType("NUMBER(10)");

                    b.HasKey("Id");

                    b.ToTable("Modulo");
                });

            modelBuilder.Entity("ESAP.Sirecec.Data.Core.Municipio", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool?>("Activo")
                        .HasColumnType("NUMBER(1)");

                    b.Property<string>("Codigo")
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<DateTime?>("CreadoEl")
                        .HasColumnType("TIMESTAMP(7)");

                    b.Property<int?>("CreadoPor")
                        .HasColumnType("NUMBER(10)");

                    b.Property<int>("DepartamentoId")
                        .HasColumnType("NUMBER(10)");

                    b.Property<string>("Descripcion")
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<DateTime?>("EditadoEl")
                        .HasColumnType("TIMESTAMP(7)");

                    b.Property<int?>("EditadoPor")
                        .HasColumnType("NUMBER(10)");

                    b.Property<string>("Nombre")
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<int?>("Orden")
                        .HasColumnType("NUMBER(10)");

                    b.HasKey("Id");

                    b.HasIndex("DepartamentoId");

                    b.ToTable("Municipio");
                });

            modelBuilder.Entity("ESAP.Sirecec.Data.Core.Municipios", b =>
                {
                    b.Property<int>("MunicipioId")
                        .HasColumnType("NUMBER(10)");

                    b.Property<bool?>("Activo")
                        .HasColumnType("NUMBER(1)");

                    b.Property<string>("DepartamentoCodigo")
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<int>("DepartamentoId")
                        .HasColumnType("NUMBER(10)");

                    b.Property<string>("DepartamentoNombre")
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<string>("MunicipioCodigo")
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<string>("MunicipioNombre")
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<int>("PaisId")
                        .HasColumnType("NUMBER(10)");

                    b.Property<string>("PaisIso1")
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<string>("PaisIso2")
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<string>("PaisNombre")
                        .HasColumnType("NVARCHAR2(2000)");

                    b.HasKey("MunicipioId");

                    b.ToTable((string)null);

                    b.ToView("Municipios", (string)null);
                });

            modelBuilder.Entity("ESAP.Sirecec.Data.Core.Nivel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool?>("Activo")
                        .HasColumnType("NUMBER(1)");

                    b.Property<DateTime?>("CreadoEl")
                        .HasColumnType("TIMESTAMP(7)");

                    b.Property<int?>("CreadoPor")
                        .HasColumnType("NUMBER(10)");

                    b.Property<string>("Descripcion")
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<DateTime?>("EditadoEl")
                        .HasColumnType("TIMESTAMP(7)");

                    b.Property<int?>("EditadoPor")
                        .HasColumnType("NUMBER(10)");

                    b.Property<int>("EscuelaId")
                        .HasColumnType("NUMBER(10)");

                    b.Property<string>("Nombre")
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<int?>("Orden")
                        .HasColumnType("NUMBER(10)");

                    b.HasKey("Id");

                    b.HasIndex("EscuelaId");

                    b.ToTable("Nivel");
                });

            modelBuilder.Entity("ESAP.Sirecec.Data.Core.Nucleo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool?>("Activo")
                        .HasColumnType("NUMBER(1)");

                    b.Property<int>("BancoId")
                        .HasColumnType("NUMBER(10)");

                    b.Property<DateTime?>("CreadoEl")
                        .HasColumnType("TIMESTAMP(7)");

                    b.Property<int?>("CreadoPor")
                        .HasColumnType("NUMBER(10)");

                    b.Property<DateTime?>("EditadoEl")
                        .HasColumnType("TIMESTAMP(7)");

                    b.Property<int?>("EditadoPor")
                        .HasColumnType("NUMBER(10)");

                    b.Property<DateTime>("FechaInicio")
                        .HasColumnType("TIMESTAMP(7)");

                    b.Property<string>("Nombre")
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<int?>("Orden")
                        .HasColumnType("NUMBER(10)");

                    b.HasKey("Id");

                    b.HasIndex("BancoId");

                    b.ToTable("Nucleo");
                });

            modelBuilder.Entity("ESAP.Sirecec.Data.Core.NucleoPrograma", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool?>("Activo")
                        .HasColumnType("NUMBER(1)");

                    b.Property<DateTime?>("CreadoEl")
                        .HasColumnType("TIMESTAMP(7)");

                    b.Property<int?>("CreadoPor")
                        .HasColumnType("NUMBER(10)");

                    b.Property<DateTime?>("EditadoEl")
                        .HasColumnType("TIMESTAMP(7)");

                    b.Property<int?>("EditadoPor")
                        .HasColumnType("NUMBER(10)");

                    b.Property<int>("NucleoId")
                        .HasColumnType("NUMBER(10)");

                    b.Property<int?>("Orden")
                        .HasColumnType("NUMBER(10)");

                    b.Property<int>("ProgramaId")
                        .HasColumnType("NUMBER(10)");

                    b.HasKey("Id");

                    b.ToTable("NucleoPrograma");
                });

            modelBuilder.Entity("ESAP.Sirecec.Data.Core.NucleosProgramas", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)");

                    b.Property<bool?>("Activo")
                        .HasColumnType("NUMBER(1)");

                    b.Property<DateTime?>("CreadoEl")
                        .HasColumnType("TIMESTAMP(7)");

                    b.Property<int?>("CreadoPor")
                        .HasColumnType("NUMBER(10)");

                    b.Property<DateTime?>("EditadoEl")
                        .HasColumnType("TIMESTAMP(7)");

                    b.Property<int?>("EditadoPor")
                        .HasColumnType("NUMBER(10)");

                    b.Property<int>("NucleoId")
                        .HasColumnType("NUMBER(10)");

                    b.Property<string>("NucleoNombre")
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<int?>("Orden")
                        .HasColumnType("NUMBER(10)");

                    b.Property<int?>("ProgramaId")
                        .HasColumnType("NUMBER(10)");

                    b.Property<string>("ProgramaNombre")
                        .HasColumnType("NVARCHAR2(2000)");

                    b.HasKey("Id");

                    b.ToTable((string)null);

                    b.ToView("NucleosProgramas", (string)null);
                });

            modelBuilder.Entity("ESAP.Sirecec.Data.Core.Pais", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool?>("Activo")
                        .HasColumnType("NUMBER(1)");

                    b.Property<int>("Codigo")
                        .HasColumnType("NUMBER(10)");

                    b.Property<DateTime?>("CreadoEl")
                        .HasColumnType("TIMESTAMP(7)");

                    b.Property<int?>("CreadoPor")
                        .HasColumnType("NUMBER(10)");

                    b.Property<DateTime?>("EditadoEl")
                        .HasColumnType("TIMESTAMP(7)");

                    b.Property<int?>("EditadoPor")
                        .HasColumnType("NUMBER(10)");

                    b.Property<string>("Iso1")
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<string>("Iso2")
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<string>("Nombre")
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<int?>("Orden")
                        .HasColumnType("NUMBER(10)");

                    b.HasKey("Id");

                    b.ToTable("Pais");
                });

            modelBuilder.Entity("ESAP.Sirecec.Data.Core.Participante", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool?>("Activo")
                        .HasColumnType("NUMBER(1)");

                    b.Property<string>("Apellidos")
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<int?>("CaracterísticaEsapId")
                        .HasColumnType("NUMBER(10)");

                    b.Property<int?>("CargoId")
                        .HasColumnType("NUMBER(10)");

                    b.Property<string>("Celular")
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<bool?>("Contratista")
                        .HasColumnType("NUMBER(1)");

                    b.Property<string>("Correo")
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<DateTime?>("CreadoEl")
                        .HasColumnType("TIMESTAMP(7)");

                    b.Property<int?>("CreadoPor")
                        .HasColumnType("NUMBER(10)");

                    b.Property<string>("Direccion")
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<int?>("DiscapacidadId")
                        .HasColumnType("NUMBER(10)");

                    b.Property<string>("DocumentoNumero")
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<DateTime?>("EditadoEl")
                        .HasColumnType("TIMESTAMP(7)");

                    b.Property<int?>("EditadoPor")
                        .HasColumnType("NUMBER(10)");

                    b.Property<int?>("EntidadId")
                        .HasColumnType("NUMBER(10)");

                    b.Property<int?>("EstadoCivilId")
                        .HasColumnType("NUMBER(10)");

                    b.Property<DateTime?>("FechaNacimiento")
                        .HasColumnType("TIMESTAMP(7)");

                    b.Property<int?>("GeneroId")
                        .HasColumnType("NUMBER(10)");

                    b.Property<int?>("GrupoEtnicoId")
                        .HasColumnType("NUMBER(10)");

                    b.Property<int?>("MunicipioId")
                        .HasColumnType("NUMBER(10)");

                    b.Property<int?>("NivelEscolarId")
                        .HasColumnType("NUMBER(10)");

                    b.Property<string>("Nombres")
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<int?>("Orden")
                        .HasColumnType("NUMBER(10)");

                    b.Property<string>("Profesion")
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<string>("Telefono")
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<int?>("TipoDocumentoId")
                        .HasColumnType("NUMBER(10)");

                    b.Property<int?>("TipoParticipanteId")
                        .HasColumnType("NUMBER(10)");

                    b.Property<int?>("TipoServidorPublicoId")
                        .HasColumnType("NUMBER(10)");

                    b.Property<int?>("VulnerabilidadId")
                        .HasColumnType("NUMBER(10)");

                    b.HasKey("Id");

                    b.ToTable("Participante");
                });

            modelBuilder.Entity("ESAP.Sirecec.Data.Core.Pregunta", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool?>("Activo")
                        .HasColumnType("NUMBER(1)");

                    b.Property<DateTime?>("CreadoEl")
                        .HasColumnType("TIMESTAMP(7)");

                    b.Property<int?>("CreadoPor")
                        .HasColumnType("NUMBER(10)");

                    b.Property<string>("Descripcion")
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<DateTime?>("EditadoEl")
                        .HasColumnType("TIMESTAMP(7)");

                    b.Property<int?>("EditadoPor")
                        .HasColumnType("NUMBER(10)");

                    b.Property<int?>("Orden")
                        .HasColumnType("NUMBER(10)");

                    b.Property<int?>("TipoEncuestaId")
                        .HasColumnType("NUMBER(10)");

                    b.Property<string>("Titulo")
                        .HasColumnType("NVARCHAR2(2000)");

                    b.HasKey("Id");

                    b.ToTable("Pregunta");
                });

            modelBuilder.Entity("ESAP.Sirecec.Data.Core.Producto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool?>("Activo")
                        .HasColumnType("NUMBER(1)");

                    b.Property<DateTime?>("CreadoEl")
                        .HasColumnType("TIMESTAMP(7)");

                    b.Property<int?>("CreadoPor")
                        .HasColumnType("NUMBER(10)");

                    b.Property<int>("DependenciaId")
                        .HasColumnType("NUMBER(10)");

                    b.Property<string>("Descripcion")
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<DateTime?>("EditadoEl")
                        .HasColumnType("TIMESTAMP(7)");

                    b.Property<int?>("EditadoPor")
                        .HasColumnType("NUMBER(10)");

                    b.Property<string>("Nombre")
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<int?>("Orden")
                        .HasColumnType("NUMBER(10)");

                    b.HasKey("Id");

                    b.ToTable("Producto");
                });

            modelBuilder.Entity("ESAP.Sirecec.Data.Core.ProductoIndicador", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool?>("Activo")
                        .HasColumnType("NUMBER(1)");

                    b.Property<DateTime?>("CreadoEl")
                        .HasColumnType("TIMESTAMP(7)");

                    b.Property<int?>("CreadoPor")
                        .HasColumnType("NUMBER(10)");

                    b.Property<DateTime?>("EditadoEl")
                        .HasColumnType("TIMESTAMP(7)");

                    b.Property<int?>("EditadoPor")
                        .HasColumnType("NUMBER(10)");

                    b.Property<int>("IndicadorId")
                        .HasColumnType("NUMBER(10)");

                    b.Property<int?>("Orden")
                        .HasColumnType("NUMBER(10)");

                    b.Property<int>("ProductoId")
                        .HasColumnType("NUMBER(10)");

                    b.HasKey("Id");

                    b.ToTable("ProductoIndicador");
                });

            modelBuilder.Entity("ESAP.Sirecec.Data.Core.Productos", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)");

                    b.Property<bool?>("Activo")
                        .HasColumnType("NUMBER(1)");

                    b.Property<DateTime?>("CreadoEl")
                        .HasColumnType("TIMESTAMP(7)");

                    b.Property<int?>("CreadoPor")
                        .HasColumnType("NUMBER(10)");

                    b.Property<int>("DependenciaId")
                        .HasColumnType("NUMBER(10)");

                    b.Property<string>("DependenciaNombre")
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<string>("Descripcion")
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<DateTime?>("EditadoEl")
                        .HasColumnType("TIMESTAMP(7)");

                    b.Property<int?>("EditadoPor")
                        .HasColumnType("NUMBER(10)");

                    b.Property<string>("Nombre")
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<int?>("Orden")
                        .HasColumnType("NUMBER(10)");

                    b.HasKey("Id");

                    b.ToTable((string)null);

                    b.ToView("Productos", (string)null);
                });

            modelBuilder.Entity("ESAP.Sirecec.Data.Core.ProductosIndicadores", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)");

                    b.Property<bool?>("Activo")
                        .HasColumnType("NUMBER(1)");

                    b.Property<DateTime?>("CreadoEl")
                        .HasColumnType("TIMESTAMP(7)");

                    b.Property<int?>("CreadoPor")
                        .HasColumnType("NUMBER(10)");

                    b.Property<DateTime?>("EditadoEl")
                        .HasColumnType("TIMESTAMP(7)");

                    b.Property<int?>("EditadoPor")
                        .HasColumnType("NUMBER(10)");

                    b.Property<int?>("IndicadorId")
                        .HasColumnType("NUMBER(10)");

                    b.Property<string>("IndicadorNombre")
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<int?>("Orden")
                        .HasColumnType("NUMBER(10)");

                    b.Property<int>("ProductoId")
                        .HasColumnType("NUMBER(10)");

                    b.Property<string>("ProductoNombre")
                        .HasColumnType("NVARCHAR2(2000)");

                    b.HasKey("Id");

                    b.ToTable((string)null);

                    b.ToView("ProductosIndicadores", (string)null);
                });

            modelBuilder.Entity("ESAP.Sirecec.Data.Core.Programa", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool?>("Activo")
                        .HasColumnType("NUMBER(1)");

                    b.Property<DateTime?>("CreadoEl")
                        .HasColumnType("TIMESTAMP(7)");

                    b.Property<int?>("CreadoPor")
                        .HasColumnType("NUMBER(10)");

                    b.Property<DateTime?>("EditadoEl")
                        .HasColumnType("TIMESTAMP(7)");

                    b.Property<int?>("EditadoPor")
                        .HasColumnType("NUMBER(10)");

                    b.Property<DateTime>("FechaInicio")
                        .HasColumnType("TIMESTAMP(7)");

                    b.Property<string>("Nombre")
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<int>("NucleoId")
                        .HasColumnType("NUMBER(10)");

                    b.Property<int?>("Orden")
                        .HasColumnType("NUMBER(10)");

                    b.HasKey("Id");

                    b.HasIndex("NucleoId");

                    b.ToTable("Programa");
                });

            modelBuilder.Entity("ESAP.Sirecec.Data.Core.Tema", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool?>("Activo")
                        .HasColumnType("NUMBER(1)");

                    b.Property<DateTime?>("CreadoEl")
                        .HasColumnType("TIMESTAMP(7)");

                    b.Property<int?>("CreadoPor")
                        .HasColumnType("NUMBER(10)");

                    b.Property<int>("DependenciaId")
                        .HasColumnType("NUMBER(10)");

                    b.Property<DateTime?>("EditadoEl")
                        .HasColumnType("TIMESTAMP(7)");

                    b.Property<int?>("EditadoPor")
                        .HasColumnType("NUMBER(10)");

                    b.Property<string>("Nombre")
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<int?>("Orden")
                        .HasColumnType("NUMBER(10)");

                    b.HasKey("Id");

                    b.ToTable("Tema");
                });

            modelBuilder.Entity("ESAP.Sirecec.Data.Core.TerritorialDepartamento", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool?>("Activo")
                        .HasColumnType("NUMBER(1)");

                    b.Property<DateTime?>("CreadoEl")
                        .HasColumnType("TIMESTAMP(7)");

                    b.Property<int?>("CreadoPor")
                        .HasColumnType("NUMBER(10)");

                    b.Property<int>("DepartamentoId")
                        .HasColumnType("NUMBER(10)");

                    b.Property<DateTime?>("EditadoEl")
                        .HasColumnType("TIMESTAMP(7)");

                    b.Property<int?>("EditadoPor")
                        .HasColumnType("NUMBER(10)");

                    b.Property<int?>("Orden")
                        .HasColumnType("NUMBER(10)");

                    b.Property<int>("TerritorialId")
                        .HasColumnType("NUMBER(10)");

                    b.HasKey("Id");

                    b.ToTable("TerritorialDepartamento");
                });

            modelBuilder.Entity("ESAP.Sirecec.Data.Core.TerritorialesDepartamentos", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)");

                    b.Property<bool?>("Activo")
                        .HasColumnType("NUMBER(1)");

                    b.Property<DateTime?>("CreadoEl")
                        .HasColumnType("TIMESTAMP(7)");

                    b.Property<int?>("CreadoPor")
                        .HasColumnType("NUMBER(10)");

                    b.Property<int?>("DepartamentoId")
                        .HasColumnType("NUMBER(10)");

                    b.Property<string>("DepartamentoNombre")
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<DateTime?>("EditadoEl")
                        .HasColumnType("TIMESTAMP(7)");

                    b.Property<int?>("EditadoPor")
                        .HasColumnType("NUMBER(10)");

                    b.Property<int?>("Orden")
                        .HasColumnType("NUMBER(10)");

                    b.Property<int>("TerritorialId")
                        .HasColumnType("NUMBER(10)");

                    b.Property<string>("TerritorialNombre")
                        .HasColumnType("NVARCHAR2(2000)");

                    b.HasKey("Id");

                    b.ToTable((string)null);

                    b.ToView("TerritorialesDepartamentos", (string)null);
                });

            modelBuilder.Entity("ESAP.Sirecec.Data.Core.ValorGeneral", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool?>("Activo")
                        .HasColumnType("NUMBER(1)");

                    b.Property<int>("Codigo")
                        .HasColumnType("NUMBER(10)");

                    b.Property<DateTime?>("CreadoEl")
                        .HasColumnType("TIMESTAMP(7)");

                    b.Property<int?>("CreadoPor")
                        .HasColumnType("NUMBER(10)");

                    b.Property<DateTime?>("EditadoEl")
                        .HasColumnType("TIMESTAMP(7)");

                    b.Property<int?>("EditadoPor")
                        .HasColumnType("NUMBER(10)");

                    b.Property<string>("Nombre")
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<int?>("Orden")
                        .HasColumnType("NUMBER(10)");

                    b.Property<string>("Tipo")
                        .HasColumnType("NVARCHAR2(2000)");

                    b.HasKey("Id");

                    b.ToTable("ValorGeneral");
                });

            modelBuilder.Entity("ESAP.Sirecec.Data.Identity.AuthRole", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("NVARCHAR2(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("NVARCHAR2(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("\"NormalizedName\" IS NOT NULL");

                    b.ToTable("AuthRoles", (string)null);
                });

            modelBuilder.Entity("ESAP.Sirecec.Data.Identity.AuthUser", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("NUMBER(10)");

                    b.Property<int?>("CompanyId")
                        .HasColumnType("NUMBER(10)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<int?>("DependenceId")
                        .HasColumnType("NUMBER(10)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("NVARCHAR2(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("NUMBER(1)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("NUMBER(1)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("NUMBER(1)");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("TIMESTAMP(7) WITH TIME ZONE");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("NVARCHAR2(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("NVARCHAR2(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("NUMBER(1)");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("NUMBER(1)");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("NVARCHAR2(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("\"NormalizedUserName\" IS NOT NULL");

                    b.ToTable("AuthUsers", (string)null);
                });

            modelBuilder.Entity("ESAP.Sirecec.Data.Identity.Users", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("NUMBER(10)");

                    b.Property<string>("CompanyAcronym")
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<int?>("CompanyId")
                        .HasColumnType("NUMBER(10)");

                    b.Property<string>("CompanyName")
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<string>("ConcurrencyStamp")
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<int?>("DependenceId")
                        .HasColumnType("NUMBER(10)");

                    b.Property<string>("DependenceName")
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<string>("Email")
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("NUMBER(1)");

                    b.Property<string>("FirstName")
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("NUMBER(1)");

                    b.Property<string>("LastName")
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("NUMBER(1)");

                    b.Property<DateTime?>("LockoutEnd")
                        .HasColumnType("TIMESTAMP(7)");

                    b.Property<string>("Name")
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<string>("NormalizedEmail")
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<string>("NormalizedUserName")
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("NUMBER(1)");

                    b.Property<int>("RoleId")
                        .HasColumnType("NUMBER(10)");

                    b.Property<string>("RoleName")
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("NUMBER(1)");

                    b.Property<string>("UserName")
                        .HasColumnType("NVARCHAR2(2000)");

                    b.HasKey("Id");

                    b.ToTable((string)null);

                    b.ToView("Usuarios", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<int>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<int>("RoleId")
                        .HasColumnType("NUMBER(10)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AuthRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<int>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<int>("UserId")
                        .HasColumnType("NUMBER(10)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AuthUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<int>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("NVARCHAR2(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("NVARCHAR2(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<int>("UserId")
                        .HasColumnType("NUMBER(10)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AuthUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<int>", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("NUMBER(10)");

                    b.Property<int>("RoleId")
                        .HasColumnType("NUMBER(10)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AuthUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<int>", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("NUMBER(10)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("NVARCHAR2(450)");

                    b.Property<string>("Name")
                        .HasColumnType("NVARCHAR2(450)");

                    b.Property<string>("Value")
                        .HasColumnType("NVARCHAR2(2000)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AuthUserTokens", (string)null);
                });

            modelBuilder.Entity("ESAP.Sirecec.Data.Core.Clasificador", b =>
                {
                    b.HasOne("ESAP.Sirecec.Data.Core.ClasificadorTipo", "ClasificadorTipo")
                        .WithMany("Clasificadores")
                        .HasForeignKey("TipoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ClasificadorTipo");
                });

            modelBuilder.Entity("ESAP.Sirecec.Data.Core.Curso", b =>
                {
                    b.HasOne("ESAP.Sirecec.Data.Core.Nivel", null)
                        .WithMany("Cursos")
                        .HasForeignKey("NivelId");
                });

            modelBuilder.Entity("ESAP.Sirecec.Data.Core.CursoAnexo", b =>
                {
                    b.HasOne("ESAP.Sirecec.Data.Core.Curso", null)
                        .WithMany("Anexos")
                        .HasForeignKey("CursoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ESAP.Sirecec.Data.Core.CursoEncuesta", b =>
                {
                    b.HasOne("ESAP.Sirecec.Data.Core.Curso", "Curso")
                        .WithMany("Encuestas")
                        .HasForeignKey("CursoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Curso");
                });

            modelBuilder.Entity("ESAP.Sirecec.Data.Core.CursoFecha", b =>
                {
                    b.HasOne("ESAP.Sirecec.Data.Core.Curso", "Curso")
                        .WithMany("Fechas")
                        .HasForeignKey("CursoId");

                    b.Navigation("Curso");
                });

            modelBuilder.Entity("ESAP.Sirecec.Data.Core.CursoTema", b =>
                {
                    b.HasOne("ESAP.Sirecec.Data.Core.Curso", "Curso")
                        .WithMany()
                        .HasForeignKey("CursoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ESAP.Sirecec.Data.Core.Tema", "Tema")
                        .WithMany()
                        .HasForeignKey("TemaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Curso");

                    b.Navigation("Tema");
                });

            modelBuilder.Entity("ESAP.Sirecec.Data.Core.Departamento", b =>
                {
                    b.HasOne("ESAP.Sirecec.Data.Core.Pais", null)
                        .WithMany("Departamentos")
                        .HasForeignKey("PaisId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ESAP.Sirecec.Data.Core.EncuestaPregunta", b =>
                {
                    b.HasOne("ESAP.Sirecec.Data.Core.Encuesta", "Encuesta")
                        .WithMany("Preguntas")
                        .HasForeignKey("EncuestaId");

                    b.HasOne("ESAP.Sirecec.Data.Core.Pregunta", "Curso")
                        .WithMany()
                        .HasForeignKey("PreguntaId");

                    b.Navigation("Curso");

                    b.Navigation("Encuesta");
                });

            modelBuilder.Entity("ESAP.Sirecec.Data.Core.Indicador", b =>
                {
                    b.HasOne("ESAP.Sirecec.Data.Core.Producto", "Producto")
                        .WithMany()
                        .HasForeignKey("ProductoId");

                    b.Navigation("Producto");
                });

            modelBuilder.Entity("ESAP.Sirecec.Data.Core.Municipio", b =>
                {
                    b.HasOne("ESAP.Sirecec.Data.Core.Departamento", null)
                        .WithMany("Municipios")
                        .HasForeignKey("DepartamentoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ESAP.Sirecec.Data.Core.Nivel", b =>
                {
                    b.HasOne("ESAP.Sirecec.Data.Core.Escuela", null)
                        .WithMany("Niveles")
                        .HasForeignKey("EscuelaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ESAP.Sirecec.Data.Core.Nucleo", b =>
                {
                    b.HasOne("ESAP.Sirecec.Data.Core.BancoPrograma", "BancoPrograma")
                        .WithMany("Nucleos")
                        .HasForeignKey("BancoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("BancoPrograma");
                });

            modelBuilder.Entity("ESAP.Sirecec.Data.Core.Programa", b =>
                {
                    b.HasOne("ESAP.Sirecec.Data.Core.Nucleo", "Nucleo")
                        .WithMany("Programas")
                        .HasForeignKey("NucleoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Nucleo");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<int>", b =>
                {
                    b.HasOne("ESAP.Sirecec.Data.Identity.AuthRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<int>", b =>
                {
                    b.HasOne("ESAP.Sirecec.Data.Identity.AuthUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<int>", b =>
                {
                    b.HasOne("ESAP.Sirecec.Data.Identity.AuthUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<int>", b =>
                {
                    b.HasOne("ESAP.Sirecec.Data.Identity.AuthRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ESAP.Sirecec.Data.Identity.AuthUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<int>", b =>
                {
                    b.HasOne("ESAP.Sirecec.Data.Identity.AuthUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ESAP.Sirecec.Data.Core.BancoPrograma", b =>
                {
                    b.Navigation("Nucleos");
                });

            modelBuilder.Entity("ESAP.Sirecec.Data.Core.ClasificadorTipo", b =>
                {
                    b.Navigation("Clasificadores");
                });

            modelBuilder.Entity("ESAP.Sirecec.Data.Core.Curso", b =>
                {
                    b.Navigation("Anexos");

                    b.Navigation("Encuestas");

                    b.Navigation("Fechas");
                });

            modelBuilder.Entity("ESAP.Sirecec.Data.Core.Departamento", b =>
                {
                    b.Navigation("Municipios");
                });

            modelBuilder.Entity("ESAP.Sirecec.Data.Core.Encuesta", b =>
                {
                    b.Navigation("Preguntas");
                });

            modelBuilder.Entity("ESAP.Sirecec.Data.Core.Escuela", b =>
                {
                    b.Navigation("Niveles");
                });

            modelBuilder.Entity("ESAP.Sirecec.Data.Core.Nivel", b =>
                {
                    b.Navigation("Cursos");
                });

            modelBuilder.Entity("ESAP.Sirecec.Data.Core.Nucleo", b =>
                {
                    b.Navigation("Programas");
                });

            modelBuilder.Entity("ESAP.Sirecec.Data.Core.Pais", b =>
                {
                    b.Navigation("Departamentos");
                });
#pragma warning restore 612, 618
        }
    }
}
